### ISSUE TITLE
Test functionality

### ISSUE THREAD

**Issue by ChargrilledChook** [ManonLef/DMA_notes#3]
**Todo**

- [ ] #2 
- [ ] #1 

You can do that by combining a checkbox `- [ ]` with an issue number `#1`

**Comment by ChargrilledChook** [comment]
Hello @ManonLef 👋

**Comment by ManonLef** [comment]
- [ ] #1  test issue task

**Comment by ChargrilledChook** [comment]
@ManonLef One other thing that may be worth playing around with is turning on discussions for this repo - it's essentially a forum but integrated with GitHub. What's nice about this is you can convert issues directly from discussions, so you can have a workflow like:

1a. Start proposal in discussion, get feedback
1b. Create draft issues on board with small ideas 
2. Create actual issues directly from discussions or draft issues on board
3. Assign and track work
4. Create PR for result (likely a doc of some kind)
5. Review and approve work, everything is documented and version controlled
6. If issues or discussions are referenced in the commit, then all the context and discussion are linked to the result
7. All the history and context for choices are linked and part of the final result :tada:
